services:
  app_bot:
    container_name: comment_bot
    mem_limit: 250m
    build:
      context: .
      dockerfile: ./Dockerfile
    image: comment_bot_image:latest
    command: sh -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/github-pr-commenter
    ports:
      - "3002:3000"
    networks:
      - blog_internal
    environment:
      - RAILS_ENV=production
    env_file:
      - .env
    tty: true
    stdin_open: true

  job:
    container_name: comment_bot_job
    mem_limit: 250m
    image: comment_bot_image:latest
    command: sh -c "bin/jobs start --mode async"
    volumes:
      - .:/github-pr-commenter
    depends_on:
      - app_bot
    networks:
      - blog_internal
    environment:
      - RAILS_ENV=production
    env_file:
      - .env

  grpc:
    container_name: comment_bot_grpc
    mem_limit: 100m
    image: comment_bot_image:latest
    command: sh -c "bin/grpc_server"
    volumes:
      - .:/github-pr-commenter
    ports:
      - "50051:50051"
    depends_on:
      - app_bot
    networks:
      - blog_internal
    environment:
      - RAILS_ENV=production
    env_file:
      - .env

networks:
  blog_internal:
    external: true
