# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto

require 'google/protobuf'


descriptor_data = "\n\rcomment.proto\x12\x07\x63omment\"\xc1\x01\n\x14\x43reateCommentRequest\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x0c\n\x04repo\x18\x02 \x01(\t\x12\x19\n\x11pullRequestNumber\x18\x03 \x01(\x05\x12?\n\tvariables\x18\x04 \x03(\x0b\x32,.comment.CreateCommentRequest.VariablesEntry\x1a\x30\n\x0eVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"8\n\x15\x43reateCommentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t2`\n\x0e\x43ommentService\x12N\n\rCreateComment\x12\x1d.comment.CreateCommentRequest\x1a\x1e.comment.CreateCommentResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Comment
  CreateCommentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("comment.CreateCommentRequest").msgclass
  CreateCommentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("comment.CreateCommentResponse").msgclass
end
