# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: comment.proto for package 'comment'

require 'grpc'
require 'comment_pb'

module Comment
  module CommentService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'comment.CommentService'

      rpc :CreateComment, ::Comment::CreateCommentRequest, ::Comment::CreateCommentResponse
    end

    Stub = Service.rpc_stub_class
  end
end
