name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Scan for known security vulnerabilities in gems used
        run: bin/bundler-audit

  lint:
    runs-on: ubuntu-latest
    env:
      RUBOCOP_CACHE_ROOT: tmp/rubocop
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Prepare RuboCop cache
        uses: actions/cache@v4
        env:
          DEPENDENCIES_HASH: ${{ hashFiles('.ruby-version', '**/.rubocop.yml', '**/.rubocop_todo.yml', 'Gemfile.lock') }}
        with:
          path: ${{ env.RUBOCOP_CACHE_ROOT }}
          key: rubocop-${{ runner.os }}-${{ env.DEPENDENCIES_HASH }}-${{ github.ref_name == github.event.repository.default_branch && github.run_id || 'default' }}
          restore-keys: |
            rubocop-${{ runner.os }}-${{ env.DEPENDENCIES_HASH }}-

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: bin/rails db:test:prepare && bundle exec rspec

      - name: Upload coverage
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  push_comment:
    needs: test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Push comment
        run: |
          PROJECT_COVERAGE=$(ruby -rjson -e '
            data = JSON.parse(File.read("coverage/coverage.json"))
            puts data["groups"]["Project"]["lines"]["covered_percent"].round(2)
          ')

          PATCH_COVERAGE=$(ruby -rjson -e '
            data = JSON.parse(File.read("coverage/coverage.json"))
            puts data["groups"]["Changed"]["lines"]["covered_percent"].round(2)
          ')

          PR_NUMBER=${{ github.event.pull_request.number }}

          CDH_API_TOKEN=${{ secrets.COMMENTER }}

          JSON=$(jq -n \
            --arg owner "${{ github.repository_owner }}" \
            --arg repo "${{ github.event.repository.name }}" \
            --argjson pr "$PR_NUMBER" \
            --argjson project "$PROJECT_COVERAGE" \
            --argjson patch "$PATCH_COVERAGE" \
            '{project_coverage:$project, patch_coverage:$patch, pull_request_number:$pr, owner:$owner, repo:$repo}')

          echo "Generated JSON: $JSON "

          curl --location 'https://codedehoc.click/gateway/comments' \
            --header "token: $CDH_API_TOKEN" \
            --header 'Content-Type: application/json' \
            --data "$JSON"
